This is makeindex, version 2.16 [MiKTeX 23.4].
Scanning style file ./Documento_maestro.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Documento_maestro.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (24 comparisons).
Generating output file Documento_maestro.acr....done (21 lines written, 0 warnings).
Output written in Documento_maestro.acr.
Transcript written in Documento_maestro.alg.
