This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./Documento_maestro.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Documento_maestro.acn....done (16 entries accepted, 0 rejected).
Sorting entries....done (65 comparisons).
Generating output file Documento_maestro.acr....done (39 lines written, 0 warnings).
Output written in Documento_maestro.acr.
Transcript written in Documento_maestro.alg.
